// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkuMq7k_IFFjlVb9HTJvaIk1uH8gYxYz8',
    appId: '1:289221288085:web:4f160665057bb8ae9b7b9c',
    messagingSenderId: '289221288085',
    projectId: 'rablo-d5e2e',
    authDomain: 'rablo-d5e2e.firebaseapp.com',
    storageBucket: 'rablo-d5e2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcIBiFG7JziS35-tq1X99W6ebjCrc5204',
    appId: '1:289221288085:android:c3c0dacd692a757c9b7b9c',
    messagingSenderId: '289221288085',
    projectId: 'rablo-d5e2e',
    storageBucket: 'rablo-d5e2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT6P_pS_R_NWvfeNNqsxDtytw8UTTctY0',
    appId: '1:289221288085:ios:7e54489d586bd4969b7b9c',
    messagingSenderId: '289221288085',
    projectId: 'rablo-d5e2e',
    storageBucket: 'rablo-d5e2e.appspot.com',
    iosBundleId: 'com.example.rablo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT6P_pS_R_NWvfeNNqsxDtytw8UTTctY0',
    appId: '1:289221288085:ios:7e54489d586bd4969b7b9c',
    messagingSenderId: '289221288085',
    projectId: 'rablo-d5e2e',
    storageBucket: 'rablo-d5e2e.appspot.com',
    iosBundleId: 'com.example.rablo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkuMq7k_IFFjlVb9HTJvaIk1uH8gYxYz8',
    appId: '1:289221288085:web:46a35a86c8dbb5389b7b9c',
    messagingSenderId: '289221288085',
    projectId: 'rablo-d5e2e',
    authDomain: 'rablo-d5e2e.firebaseapp.com',
    storageBucket: 'rablo-d5e2e.appspot.com',
  );

}